# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

# required as all of the jobs need to have a tag filter for some reason
tag_filters: &tag_filters
  filters:
      tags:
        only: /.*/

jobs:
  build_agent:
    docker:
      - image: cimg/go:1.14
    # needed to build docker images, attach mount points, etc
    steps:
      - checkout
      - setup_remote_docker
      - run: make container
      - run: make test
      - run: e2e-tests/test.sh
      - run:
          name: "Deploy on tagged master push"
          command: |
              echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin;
              make push;
              make push-head;


# Orchestrate or schedule a set of jobs, see https://circleci.com/docs/2.0/workflows/
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_agent: *tag_filters
